services:
  jobhunt:
    image: thor.docker.registry:5000/jobhunt:latest
    container_name: jobhunt
    networks:
      - MyDockerNetwork
    ports:
      - "5000"
    restart: unless-stopped

  jobhuntapi:
    image: thor.docker.registry:5000/jobhuntapi:latest
    container_name: jobhuntapi
    networks:
      - MyDockerNetwork
    ports:
      - "5000"
    restart: "unless-stopped"

  nginx_jobhunt:
    image: nginx:latest
    container_name: nginx_jobhunt
    networks:
      MyDockerNetwork:
        ipv4_address: 192.168.3.102
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jobhunt
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  MyDockerNetwork:
    external: true