version: "3.8"

services:
  jobhunt:
    build:
      context: .
    image: jobhunt:latest
    networks:
      - My_Docker-Network
      # - My_2ndDocker_Network
    ports:
      - "5000"
    restart: unless-stopped
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt

  nginx_jobhunt:
    image: nginx:latest
    container_name: nginx_jobhunt
    networks:
      My_Docker_Network:
        ipv4_address: 192.168.2.102
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - jobhunt
    ports:
      - "80:80"
#      - "443:443"
    restart: unless-stopped

networks:
  My_2ndDocker_Network:
    external: true

  
